//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIForCustomerTelephone.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CustomerPhoneEntities : DbContext
    {
        public CustomerPhoneEntities()
            : base("name=CustomerPhoneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerPhone> CustomerPhones { get; set; }
    
        public virtual ObjectResult<GetAllPhoneNumbers_Result> GetAllPhoneNumbers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllPhoneNumbers_Result>("GetAllPhoneNumbers");
        }
    }
}
