//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIForCustomerTelephone.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPhone
    {
        public int phoneId { get; set; }
        public int customerId { get; set; }
        public string customerPhone { get; set; }
        public string phoneStaus { get; set; }
        public string phoneDesc { get; set; }
    }
}
